# Generated by Django 5.2.5 on 2025-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='driver_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='driving_exp',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='car_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='insurance_cost',
        ),
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tariff',
            field=models.CharField(choices=[('econom', 'Эконом'), ('standart', 'Стандарт'), ('premium', 'Премиум')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='car_type',
            field=models.CharField(choices=[('car', 'Легковой'), ('truck', 'Грузовой'), ('moto', 'Мото')], max_length=20),
        ),
    ]
